export const menuResources = {
  en: {
    file: 'File',
    edit: 'Edit',
    view: 'View',
    window: 'Window',
    help: 'Help',
    newWorkspace: 'New tab',
    closeWorkspace: 'Close tab',
    connections: 'Connections',
    settings: 'Settings',
    repository: 'Open GitHub repository',
    about: 'About OpenSCP',
    version: 'Version',
    openGitHub: 'Open GitHub',
    close: 'Close',
    minimize: 'Minimize',
    zoomWindow: 'Zoom',
    bringAllToFront: 'Bring All to Front',
    quit: 'Quit',
    undo: 'Undo',
    redo: 'Redo',
    cut: 'Cut',
    copy: 'Copy',
    paste: 'Paste',
    selectAll: 'Select all',
    resetZoom: 'Actual size',
    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
    togglefullscreen: 'Full screen',
  },
  ru: {
    file: 'Файл',
    edit: 'Правка',
    view: 'Вид',
    window: 'Окно',
    help: 'Справка',
    newWorkspace: 'Новая вкладка',
    closeWorkspace: 'Закрыть вкладку',
    connections: 'Подключения',
    settings: 'Настройки',
    repository: 'Открыть репозиторий GitHub',
    about: 'О программе OpenSCP',
    version: 'Версия',
    openGitHub: 'Открыть GitHub',
    close: 'Закрыть',
    minimize: 'Свернуть',
    zoomWindow: 'Развернуть',
    bringAllToFront: 'Все окна на передний план',
    quit: 'Выход',
    undo: 'Отменить',
    redo: 'Повторить',
    cut: 'Вырезать',
    copy: 'Копировать',
    paste: 'Вставить',
    selectAll: 'Выделить всё',
    resetZoom: 'Исходный масштаб',
    zoomIn: 'Увеличить',
    zoomOut: 'Уменьшить',
    togglefullscreen: 'Полный экран',
  },
};
